### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by xmha97** [pouriap/Thunderbird-IranianDate#2]
سلام، من نمی‌تونم این اکستنشن رو نصب کنم
![image](https://user-images.githubusercontent.com/23485114/108492929-f7189900-72ba-11eb-89f3-ad9890efec3d.png)

**Comment by pouriap** [comment]
سلام
نسخه تاندربردتون چند هست؟
اگر بالای 60 هست این اکستنشن باهاش کار نمیکنه و باید از تقویم ماهور(که داخل تصویر خودتون هم مشخصه) استفاده کنید که https://github.com/mhdzli زحمت کشیدن از روی همین اکستنشن نوشتن.

**Comment by xmha97** [comment]
نسخه‌ی تاندربردم:
![image](https://user-images.githubusercontent.com/23485114/108494338-a7d36800-72bc-11eb-9e51-720567e2a9b4.png)
ممنون از شما، ماهور رو نصب کردم.
